records per page defaulted to 10 query param
uwbaddev/baddie-match pull request #67
Opened 2023-03-08 16:28 UTC by choiii-darren

#63

2023-03-09 01:07 UTC, ivanccheng commented
gonna deploy to take a look

2023-03-09 23:09 UTC, choiii-darren commented
woops i griefed i fixed now

2023-03-10 16:25 UTC, ivanccheng requested changes
![image](https://user-images.githubusercontent.com/67285549/224368404-99df2dcd-22bf-4307-8c8c-4b269fefe12e.png)
looks like the reason why it's returning a blank is bc the request is still requesting the old page num. 

flow: 
Default 10 per page, requests page 42
IF then Switches to 20 per page, but still requests 42, no data there. Should change the request page to reflect the new data per page

IMO an easy fix to this is simple refresh the route and set the page to 1 when `perPage` is changed, you can do whatever you like though

2023-03-10 16:25 UTC, ivanccheng commented on front-end/src/components/Results.js
> +                            }}>20</Dropdown.Item>
should also update the active page, to 1 or do some math to get the current page based on the new per page

2023-03-12 16:58 UTC, ivanccheng approved these changes
Looks good to me!

nit/future improvement: 
We can add the "loading/retrieving data" text/modal when switching in between pages, to accomodate slower network connections or slower performance due to higher usage

2023-03-12 16:58 UTC, ivanccheng commented
Remember to use squash and merge!

2023-03-13 01:07 UTC, merged